/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useConvexHull, useTrimesh } from "../../src";
import { useRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    plinko: THREE.Mesh;
    container: THREE.Mesh;
    wall: THREE.Mesh;
  };
  materials: {
    blue: THREE.MeshStandardMaterial;
    Material: THREE.MeshPhysicalMaterial;
    ["Material.001"]: THREE.MeshPhysicalMaterial;
  };
};

export default function Plinko({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);

  const { nodes, materials } = useGLTF(
    // @ts-ignore
    new URL("plinko.glb", import.meta.url).toString()
  ) as unknown as GLTFResult;

  const [plinko] = useTrimesh.fromMesh(nodes.plinko, {
    type: "fixed",
    position: [0, 7.58, -1.06],
  });

  const [wall] = useConvexHull.fromMesh(nodes.wall, {
    type: "fixed",
    position: [0, -0.39, 0.44],
  });

  const [container] = useTrimesh.fromMesh(nodes.container, {
    type: "fixed",
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        ref={plinko}
        geometry={nodes.plinko.geometry}
        material={materials.blue}
        material-color="blue"
        position={[0, 7.58, -1.06]}
        castShadow
        receiveShadow
      />
      <mesh
        ref={container}
        geometry={nodes.container.geometry}
        material={materials.Material}
        castShadow
      />
      <mesh
        ref={wall}
        geometry={nodes.wall.geometry}
        material={materials["Material.001"]}
        position={[0, -0.39, 0.44]}
      />
    </group>
  );
}
