/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useEffect, useRef } from "react";
import { Group, Mesh, MeshPhysicalMaterial, MeshStandardMaterial } from "three";
import { RigidBody } from "@react-three/rapier";
import { useDemo } from "../../App";
import { useResetOrbitControls } from "../../hooks/use-reset-orbit-controls";

type GLTFResult = GLTF & {
  nodes: {
    plinko: Mesh;
    container: Mesh;
    wall: Mesh;
  };
  materials: {
    blue: MeshStandardMaterial;
    Material: MeshPhysicalMaterial;
    ["Material.001"]: MeshPhysicalMaterial;
  };
};

export default function Plinko({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null);
  const { orbitControlRef } = useDemo();

  const { nodes, materials } = useGLTF(
    // @ts-ignore
    new URL("../../models/plinko.glb", import.meta.url).toString()
  ) as unknown as GLTFResult;

  useResetOrbitControls();

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[0, 0, 0.75]}
      scale={1}
    >
      <RigidBody type="fixed" colliders="trimesh">
        <group scale={1}>
          <mesh
            geometry={nodes.plinko.geometry}
            material={materials.blue}
            material-color="blue"
            castShadow
            receiveShadow
            rotation={nodes.plinko.rotation}
            position={nodes.plinko.position}
          />
        </group>
      </RigidBody>
      <RigidBody type="fixed" colliders={"trimesh"}>
        <mesh
          geometry={nodes.container.geometry}
          material={materials.Material}
          castShadow
        />
      </RigidBody>
      <RigidBody type="fixed" colliders={"hull"}>
        <mesh
          geometry={nodes.wall.geometry}
          material={materials["Material.001"]}
          rotation={nodes.wall.rotation}
          position={nodes.wall.position}
        />
      </RigidBody>
    </group>
  );
}
