name: Runs Vitest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable corepack  
        run: corepack enable
      
      - name: Install deps
        run: yarn --immutable
      
      - name: "Run tests"
        run: npm run test
